matric2016/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mresults.urls')),
    path('mresults/', include('mresults.urls')),
]

mresults/urls.py
from django.urls import path

from . import views

app_name = 'mresults'
urlpatterns = [
    path('', views.index, name='index'),
    path('trends/', views.trends, name='trends'),
    path('each/', views.each_school, name='each'),
    path('debug/', views.debg, name='debg'),
]

mresults/models.py
from django.db import models

# Create your models here.
class AllResults(models.Model):
    wrote = models.PositiveIntegerField(default=0)
    passed = models.PositiveIntegerField(default=0)
    year = models.CharField(max_length=8)
    name = models.CharField(max_length = 50)

mresults/views.py
from django.shortcuts import render
from .models import *
from django.db.models import *
import simplejson

import pandas as pd
import numpy as np

# Each question dicovered in EDA must have its won view

# Important info to the public - summary
# Bonus: prediction model
def index(request):
    matric_results = pd.DataFrame()
    matric_results['Yearly'] = np.asarray ( list(AllResults.objects.values_list('year', flat=True)) )
    matric_results['Wrote'] = np.asarray ( list(AllResults.objects.values_list('wrote', flat=True)) )
    matric_results['Passed'] = np.asarray ( list(AllResults.objects.values_list('passed', flat=True)) )
    matric_results['Name'] = np.asarray ( list(AllResults.objects.values_list('name', flat=True)) )

    distinct_years = list ( AllResults.objects.values_list('year', flat=True).distinct() )
    numDate = []
    for year in distinct_years:
        numDate.append(int(year))
    numDate = sorted(numDate, reverse=True)

    dates = []
    for year in numDate:
        dates.append(str(year))

    total_pass = []
    total_wrote = []
    for year in dates:
        total_wrote.append( AllResults.objects.filter(year=year).aggregate(Sum('wrote'))['wrote__sum'] )
        total_pass.append( AllResults.objects.filter(year=year).aggregate(Sum('passed') )['passed__sum'] )

    #byYear = AllResults.objects.filter(year='2014').aggregate(Sum('wrote'))
    n_average = np.array(list(total_pass))/ np.array(list(total_wrote)) * 100
    n_average = np.around(n_average,2)

    context = {'n_average':list(n_average.tolist()), 'current_pass':n_average.tolist()[0],
                'prev_pass':n_average.tolist()[1],
                'passed':simplejson.dumps(list(total_pass)),
                'wrote':simplejson.dumps(list(total_wrote)),
                'category_list':numDate}

    return render(request, 'mresults/index.html', context)

# Debugging view
def debg(request):
    matric_results = pd.DataFrame()
    matric_results['Yearly'] = np.asarray ( list(AllResults.objects.values_list('year', flat=True)) )
    matric_results['Wrote'] = np.asarray ( list(AllResults.objects.values_list('wrote', flat=True)) )
    matric_results['Passed'] = np.asarray ( list(AllResults.objects.values_list('passed', flat=True)) )
    matric_results['Name'] = np.asarray ( list(AllResults.objects.values_list('name', flat=True)) )

    distinct_years = list ( AllResults.objects.values_list('year', flat=True).distinct() )
    numDate = []
    for year in distinct_years:
        numDate.append(int(year))
    numDate = sorted(numDate)
   # distinct_years = sorted(distinct_years)

    total_pass = []
    total_wrote = []
    for year in distinct_years:
        total_wrote.append( AllResults.objects.filter(year=year).aggregate(Sum('wrote')).values() )
        total_pass.append( AllResults.objects.filter(year=year).aggregate(Sum('passed') )['passed__sum'] )

    byYear = AllResults.objects.filter(year='2014').aggregate(Sum('wrote'))

    context = {'yearly_national':byYear,'category':distinct_years,
                'passed':simplejson.dumps(list(total_pass)),
                'sizelist':len(distinct_years)}

    return render(request, 'mresults/debg.html', context)

# Calulations - Statistical calculations and trends
def trends(request):
    context = {}
    return render(request, 'mresults/chart.html', context)

# Trends / school
def each_school(request):
    context = {}
    return render(request, 'mresults/table.html', context)

mresults/templates/mresults/chart.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Statistics for matric results 2016</title>
	<!-- Bootstrap Styles-->
    <link href="../static/mresults/assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FontAwesome Styles-->
    <link href="../static/mresults/assets/css/font-awesome.css" rel="stylesheet" />
     <!-- Morris Chart Styles-->
    <link href="../static/mresults/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
        <!-- Custom Styles-->
    <link href="../static/mresluts/assets/css/custom-styles.css" rel="stylesheet" />
     <!-- Google Fonts-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'mresults:index' ">Summary of results</a>
            </div>

            <ul class="nav navbar-top-links navbar-right">

            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="ui-elements.html"><i class="fa fa-desktop"></i> UI Elements</a>
                    </li>
					<li>
                        <a href="chart.html" class="active-menu"><i class="fa fa-bar-chart-o"></i> Charts</a>
                    </li>
                    <li>
                        <a href="tab-panel.html"><i class="fa fa-qrcode"></i> Tabs & Panels</a>
                    </li>
                    
                    <li>
                        <a href="table.html"><i class="fa fa-table"></i> Responsive Tables</a>
                    </li>
                    <li>
                        <a href="form.html"><i class="fa fa-edit"></i> Forms </a>
                    </li>


        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Charts <small>Show up your stats</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
             
                <div class="row"> 
                    
                      
                               <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Bar Chart
                        </div>
                        <div class="panel-body">
                            <div id="morris-bar-chart"></div>
                        </div>
                    </div>            
                </div>
                      <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Area Chart
                        </div>
                        <div class="panel-body">
                            <div id="morris-area-chart"></div>
                        </div>
                    </div>            
                </div> 
                
           </div>
                 <!-- /. ROW  -->
                <div class="row">                     
                      
                               <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Donut Chart
                        </div>
                        <div class="panel-body">
                            <div id="morris-line-chart"></div>
                        </div>
                    </div>            
                </div>
                      <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Line Chart
                        </div>
                        <div class="panel-body">                            
							<div id="morris-donut-chart"></div>
                        </div>
                    </div>            
                </div> 
                
           </div>
                 <!-- /. ROW  -->
				 <footer><p>All right reserved: <a href="http://webthemez.com">WebThemez</a></p></footer>
				</div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>
     <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="../static/mresults/assets/js/jquery-1.10.2.js"></script>
      <!-- Bootstrap Js -->
    <script src="../static/mresults/assets/js/bootstrap.min.js"></script>
    <!-- Metis Menu Js -->
    <script src="../static/mresults/assets/js/jquery.metisMenu.js"></script>
     <!-- Morris Chart Js -->
     <script src=".../static/mresults/assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="../static/mresults/assets/js/morris/morris.js"></script>
      <!-- Custom Js -->
    <script src="../static/mresults/assets/js/custom-scripts.js"></script>
    
   
</body>
</html>

mresults/templates/mresults/debg.html
<p>{{yearly_national }}</p>

<p>{{ category }}</p>

<p>{{passed}}</p>

<p>{{sizelist}}</p>

mresults/templates/mresults/index.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dpt of Basic education SA</title>
    <!--Load Hicharts Libraries-->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>


    <!-- Bootstrap Styles-->
    <link href="static/mresults/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="static/mresults/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="static/mresults/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="static/mresults/assets/css/custom-styles.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div id="wrapper" style="background-color:#09224c">
        <nav class="navbar navbar-default top-navbar" role="navigation" style="background-color:#09224c">
            <div class="navbar-header" style="background:black">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'mresults:index' %}">Matric 2016</a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <span><a href="#" class="fa fa-whatsapp fa-3x"></a></span>
                <span><a href="#" class="fa fa-twitter fa-3x"></a></span>
                <span><a href="#" class="fa fa-linkedin fa-3x"></a></span>
                <span><a href="#" class="fa fa-facebook fa-3x"></a></span>
            </ul>
        </nav>
        <!--/. NAV TOP  -->

        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a class="active-menu" href="{% url 'mresults:index' %}"><i class="fa fa-arrow-right"></i> Summary</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i> Stats</a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-sitemap" aria-hidden="true"></i> View by<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Province</a>
                            </li>
                            <li>
                                <a href="#">District</a>
                            </li>
                            <li>
                                <a href="#">Ruling Party<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">ANC</a>
                                    </li>
                                    <li>
                                        <a href="#">DA</a>
                                    </li>
                                    <li>
                                        <a href="#">EFF</a>
                                    </li>

                                </ul>

                            </li>
                        </ul>
                    </li>

					<li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i> Analysis</a>
                    </li>
            
                    <li style="width:100%;">
                        <input type="text" placeholder="Search.." name="search">
                    </li>
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Home <small>Summary of results</small>
                        </h1>
                    </div>
                </div>
                <!-- /. ROW  -->

                <div class="row">
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-body">
                                <i class="fa fa-bar-chart-o fa-5x"></i>
                                <h3>{{current_pass}}<span>%</span></h3>
                            </div>
                            <div class="panel-footer back-footer-green">
                                National Pass Rate

                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue">
                            <div class="panel-body">
                                <i class="fa fa-sort-amount-desc fa-5x"></i>
                                <h3>{{prev_pass}}<span>%</span></h3>
                            </div>
                            <div class="panel-footer back-footer-blue">
                                Previous year

                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-body">
                                <i class="fa fa-sort-desc fa-5x"></i>
                                <h3>Gauteng </h3>
                            </div>
                            <div class="panel-footer back-footer-green">
                                Highest

                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-red">
                            <div class="panel-body">
                                <i class="fa fa-sort-asc fa-5x"></i>
                                <h3>Eastern Cape </h3>
                            </div>
                            <div class="panel-footer back-footer-red">
                                Lowest

                            </div>
                        </div>
                    </div>
                </div>


                <div class="row">


                    <div class="col-md-9 col-sm-12 col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                National Yearly Performance
                            </div>
                            <div class="panel-body">
                                <div id="yearly_bar"></div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Top 5 Schools
                            </div>
                            <div class="panel-body">
                                <div id="top5_schools"></div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /. ROW  -->
				
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
        <footer><p>All rights reserved:<a href="http://webthemez.com">WebThemez</a></p></footer>
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="static/mresults/assets/js/jquery-1.10.2.js"></script>
    <!-- Bootstrap Js -->
    <script src="static/mresults/assets/js/bootstrap.min.js"></script>
    <!-- Metis Menu Js -->
    <script src="static/mresults/assets/js/jquery.metisMenu.js"></script>
    <!-- Morris Chart Js -->
    <script src="static/mresults/assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="static/mresults/assets/js/morris/morris.js"></script>
    <!-- Custom Js -->
    <script src="static/mresults/assets/js/custom-scripts.js"></script>

<script>
        var category_list = [];
        category_list = {{category_list | safe }}.slice(0,10);
        var passed = {{ passed | safe}}.slice(0,10);
        var wrote = {{ wrote | safe}}.slice(0,10);

        var n_avg = {{ n_average | safe}}.slice(0,10);

        Highcharts.chart('yearly_bar', {
            title: {
                text: '.'
            },
            xAxis: {
                categories: category_list
            },    yAxis: [{ // Primary yAxis
                labels: {
                    format: '{value}%',
                    style: {
                        color: Highcharts.getOptions().colors[2]
                    }
                },
                title: {
                    text: 'National average',
                    style: {
                        color: Highcharts.getOptions().colors[2]
                    }
                },
                opposite: true
        
            }, { // Secondary yAxis
                gridLineWidth: 0,
                title: {
                    text: 'Number of students',
                    style: {
                        color: Highcharts.getOptions().colors[0]
                    }
                },
                labels: {
                    format: '{value} ',
                    style: {
                        color: Highcharts.getOptions().colors[0]
                    }
                }
        
            }],
            labels: {
                items: [{
                    html: '.',
                    style: {
                        left: '50px',
                        top: '18px',
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                    }
                }]
            },
            series: [{
                type: 'column',
                name: 'Total Enrollment',
                color: '#09224c',
                yAxis: 1,
                data: wrote
            }, {
                type: 'column',
                name: 'No of passes',
                color: '#00ce71',
                yAxis: 1,
                data: passed
            },  {
                type: 'spline',
                name: 'Average',
                color:'#0ba825',
                yAxis: 0,
                data: n_avg,
                marker: {
                    lineWidth: 4,
                    lineColor: '#ff0000',
                    fillColor: 'white'
                }
            }]
        });
        
</script>


    
    <script>
        // Build the chart
Highcharts.chart('top5_schools', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: '.'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: false
            },
            showInLegend: true
        }
    },
    series: [{
        name: '2016 Pass Rate',
        colorByPoint: true,
        data: [{
            name: 'Mbilwi',
            y: 61.41,
            sliced: true,
            selected: true
        }, {
            name: 'Zye',
            y: 11.84
        }, {
            name: 'Capricon',
            y: 10.85
        }, {
            name: 'Daveton',
            y: 4.67
        }, {
            name: 'Cape Town',
            y: 4.18
        }]
    }]
});
    </script>

</body>
<style>
    /* Facebook */
.fa-facebook {
    background: #3B5998;
    color: white;

}

/* Twitter */
.fa-twitter {
    background: #55ACEE;
    color: white;
    text-align: center;
}
</style>

</html>

mresults/templates/mresults/main_index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'mresults/main_style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{%  url 'mresults:index' %}">{{ question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}